use axum::{
    extract::{Extension, Path, Query, State},
    http::StatusCode,
    response::Json,
};
use serde::{Deserialize, Serialize};
use sqlx::{Pool, Sqlite};
use std::collections::HashSet;

use crate::middleware::{auth::AuthInfo, path_permission};
use crate::services::tagging::service::{PendingTagSuggestion, ReviewTagSuggestionResult};
use crate::services::tagging::{
    ReviewTagSuggestion, TagSuggestionReviewAction, TaggingService, UndoTaggingRunResult,
};
use crate::services::ContentAnalysisService;

const DEFAULT_BACKFILL_LIMIT: u32 = 100;
const MAX_BACKFILL_LIMIT: u32 = 500;

#[derive(Debug, Default, Deserialize)]
#[serde(default, rename_all = "camelCase")]
pub struct PendingTagSuggestionsQuery {
    pub archive_id: Option<String>,
    pub limit: Option<u32>,
    pub include_auto_applied: bool,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReviewTagSuggestionRequest {
    pub action: TagSuggestionReviewAction,
    pub edited_name: Option<String>,
    pub edited_namespace: Option<String>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct EnqueueArchiveTaggingResponse {
    pub queued: bool,
}

#[derive(Debug, Default, Deserialize)]
#[serde(default, rename_all = "camelCase")]
pub struct TaggingBackfillRequest {
    /// Supplying ids runs a selected batch. Without ids, `cursor` advances through the library
    /// in stable `(created_at, id)` order.
    pub archive_ids: Option<Vec<String>>,
    pub limit: Option<u32>,
    pub cursor: Option<String>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TaggingBackfillResponse {
    pub attempted: u32,
    pub queued: u32,
    pub skipped: u32,
    pub failed: u32,
    pub has_more: bool,
    pub next_cursor: Option<String>,
}

/// Lists pending suggestions generated by the current provenance-aware tagging workflow.
/// This endpoint is registered in the admin router because it spans the full library.
pub async fn list_pending_suggestions(
    State(pool): State<Pool<Sqlite>>,
    Query(query): Query<PendingTagSuggestionsQuery>,
) -> Result<Json<Vec<PendingTagSuggestion>>, StatusCode> {
    let limit = query.limit.unwrap_or(100).clamp(1, 200);
    TaggingService::new(pool)
        .list_suggestions(
            query.archive_id.as_deref(),
            limit,
            query.include_auto_applied,
        )
        .await
        .map(Json)
        .map_err(|error| {
            tracing::error!(error = %error, "failed to list pending AI tag suggestions");
            StatusCode::INTERNAL_SERVER_ERROR
        })
}

/// Records one human decision. The audited reviewer is obtained from the JWT rather than the
/// request body.
pub async fn review_suggestion(
    State(pool): State<Pool<Sqlite>>,
    Path(suggestion_id): Path<String>,
    Extension(auth): Extension<AuthInfo>,
    Json(request): Json<ReviewTagSuggestionRequest>,
) -> Result<Json<ReviewTagSuggestionResult>, StatusCode> {
    let exists = sqlx::query_scalar::<_, i64>(
        "SELECT 1 FROM ai_tag_suggestions WHERE id = ? LIMIT 1",
    )
    .bind(&suggestion_id)
    .fetch_optional(&pool)
    .await
    .map_err(|error| {
        tracing::error!(suggestion_id, error = %error, "failed to look up AI tag suggestion");
        StatusCode::INTERNAL_SERVER_ERROR
    })?;
    if exists.is_none() {
        return Err(StatusCode::NOT_FOUND);
    }

    TaggingService::new(pool)
        .review_suggestion(
            &suggestion_id,
            ReviewTagSuggestion {
                action: request.action,
                reviewed_by: Some(auth.user_id),
                edited_name: request.edited_name,
                edited_namespace: request.edited_namespace,
            },
        )
        .await
        .map(Json)
        .map_err(|error| {
            tracing::warn!(suggestion_id, error = %error, "AI tag suggestion review was rejected");
            StatusCode::CONFLICT
        })
}

/// Undoes the applications associated with one provenance run. The service preserves tags that
/// existed before the run and tags retained by another active AI application.
pub async fn undo_run(
    State(pool): State<Pool<Sqlite>>,
    Path(run_id): Path<String>,
    Extension(auth): Extension<AuthInfo>,
) -> Result<Json<UndoTaggingRunResult>, StatusCode> {
    let exists = sqlx::query_scalar::<_, i64>("SELECT 1 FROM ai_tagging_runs WHERE id = ? LIMIT 1")
        .bind(&run_id)
        .fetch_optional(&pool)
        .await
        .map_err(|error| {
            tracing::error!(run_id, error = %error, "failed to look up AI tagging run");
            StatusCode::INTERNAL_SERVER_ERROR
        })?;
    if exists.is_none() {
        return Err(StatusCode::NOT_FOUND);
    }

    TaggingService::new(pool)
        .undo_run(&run_id, Some(auth.user_id))
        .await
        .map(Json)
        .map_err(|error| {
            tracing::error!(run_id, error = %error, "failed to undo AI tagging run");
            StatusCode::INTERNAL_SERVER_ERROR
        })
}

/// Explicitly reconciles one archive through the shared content pipeline. Unlike global review
/// operations, this route is available to a user who has permission for the archive's path.
pub async fn enqueue_archive_tagging(
    State(pool): State<Pool<Sqlite>>,
    Path(archive_id): Path<String>,
    Extension(auth): Extension<AuthInfo>,
) -> Result<(StatusCode, Json<EnqueueArchiveTaggingResponse>), StatusCode> {
    path_permission::authorize_archive_access(&pool, &auth, &archive_id).await?;
    let queued = ContentAnalysisService::new(pool)
        .enqueue_for_archive(&archive_id)
        .await
        .map_err(|error| {
            tracing::warn!(archive_id, error = %error, "failed to enqueue AI tag workflow");
            StatusCode::CONFLICT
        })?;
    Ok((
        StatusCode::ACCEPTED,
        Json(EnqueueArchiveTaggingResponse { queued }),
    ))
}

/// Queues one bounded library batch for content-pipeline reconciliation. Queue-level deduplication
/// makes repeating a cursor or overlapping selected batches harmless.
pub async fn backfill(
    State(pool): State<Pool<Sqlite>>,
    Json(request): Json<TaggingBackfillRequest>,
) -> Result<Json<TaggingBackfillResponse>, StatusCode> {
    let limit = request
        .limit
        .unwrap_or(DEFAULT_BACKFILL_LIMIT)
        .clamp(1, MAX_BACKFILL_LIMIT);
    let (archive_ids, has_more, next_cursor) = if let Some(requested_ids) = request.archive_ids {
        let mut seen = HashSet::new();
        let ids = requested_ids
            .into_iter()
            .map(|id| id.trim().to_string())
            .filter(|id| !id.is_empty())
            .filter(|id| seen.insert(id.clone()))
            .collect::<Vec<_>>();
        if ids.len() > limit as usize {
            tracing::warn!(
                requested = ids.len(),
                limit,
                "AI tag backfill request exceeds batch limit"
            );
            return Err(StatusCode::BAD_REQUEST);
        }
        (ids, false, None)
    } else {
        if let Some(cursor) = request.cursor.as_deref() {
            let cursor_exists = sqlx::query_scalar::<_, i64>(
                "SELECT 1 FROM archives WHERE id = ? LIMIT 1",
            )
            .bind(cursor)
            .fetch_optional(&pool)
            .await
            .map_err(|error| {
                tracing::error!(cursor, error = %error, "failed to validate AI tag backfill cursor");
                StatusCode::INTERNAL_SERVER_ERROR
            })?;
            if cursor_exists.is_none() {
                return Err(StatusCode::BAD_REQUEST);
            }
        }
        let rows = sqlx::query_scalar::<_, String>(
            "SELECT id FROM archives \
             WHERE ? IS NULL OR (\
                 created_at > (SELECT created_at FROM archives WHERE id = ?) OR \
                 (created_at = (SELECT created_at FROM archives WHERE id = ?) AND id > ?)\
             ) \
             ORDER BY created_at ASC, id ASC LIMIT ?",
        )
        .bind(&request.cursor)
        .bind(&request.cursor)
        .bind(&request.cursor)
        .bind(&request.cursor)
        .bind(i64::from(limit) + 1)
        .fetch_all(&pool)
        .await
        .map_err(|error| {
            tracing::error!(error = %error, "failed to select AI tag backfill batch");
            StatusCode::INTERNAL_SERVER_ERROR
        })?;
        let has_more = rows.len() > limit as usize;
        let archive_ids = rows.into_iter().take(limit as usize).collect::<Vec<_>>();
        let next_cursor = has_more.then(|| archive_ids.last().cloned()).flatten();
        (archive_ids, has_more, next_cursor)
    };

    let workflow = ContentAnalysisService::new(pool);
    let mut response = TaggingBackfillResponse {
        attempted: archive_ids.len() as u32,
        queued: 0,
        skipped: 0,
        failed: 0,
        has_more,
        next_cursor,
    };
    for archive_id in archive_ids {
        match workflow.enqueue_for_archive(&archive_id).await {
            Ok(true) => response.queued += 1,
            Ok(false) => response.skipped += 1,
            Err(error) => {
                response.failed += 1;
                tracing::warn!(archive_id, error = %error, "failed to enqueue archive during AI tag backfill");
            }
        }
    }
    Ok(Json(response))
}
